let names = [];

names.append("bonoro");
names.append("bozonaro");
names.append("bolsochato");
names.append("bonossauro");
names.append("balsenario camboriu");
names.append("salnorabo");
names.append("bolsonabo");
names.append("chatonaro");
names.append("capironaro");
names.append("bolsonazi");
names.append("bolismo");
names.append("bolo");
names.append("bolovo");
names.append("bolsoralho");
names.append("fetonaro");
names.append("bostonaro");
names.append("trumpnaro");
names.append("fuzilnaro");
names.append("bozotario");
names.append("malbonaro");
names.append("esfaquenaro");
names.append("bololo");
names.append("bulbalssaujo");
names.append("bolivario");
names.append("botuslismonaro");
names.append("pocketnaro");
